---
development:
  cloud_name: badeeb
  api_key: '326938331546915'
  api_secret: Ms9kbR5YYuc30pHA_cuQX1sHjPI
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: badeeb
  api_key: '326938331546915'
  api_secret: Ms9kbR5YYuc30pHA_cuQX1sHjPI
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: badeeb
  api_key: '326938331546915'
  api_secret: Ms9kbR5YYuc30pHA_cuQX1sHjPI
  enhance_image_tag: true
  static_image_support: false
