class Setting < ApplicationRecord

	validates :key, :value, presence: true

	COMPANY_ABOUT = 'COMPANY_ABOUT'
	COMPANY_TELEPHONE = 'COMPANY_TELEPHONE'
	COMPANY_FAX = 'COMPANY_FAX'
	COMPANY_WEBSITE = 'COMPANY_WEBSITE'
	COMPANY_FACEBOOK = 'COMPANY_JUMIA'
	COMPANY_WHATSAPP = 'COMPANY_WHATSAPP'

	MAX_VENDORS_NO = 'MAX_VENDORS_NO'


end
