class Setting < ApplicationRecord

	COMPANY_ABOUT = 'COMPANY_ABOUT'
	COMPANY_TELEPHONE = 'COMPANY_TELEPHONE'
	COMPANY_FAX = 'COMPANY_FAX'
	COMPANY_WEBSITE = 'COMPANY_WEBSITE'
	COMPANY_JUMIA = 'COMPANY_JUMIA'
	COMPANY_SOUQ = 'COMPANY_SOUQ'
	COMPANY_WHATSAPP = 'COMPANY_WHATSAPP'

end
